[user@sd-template-builder ~]$ sudo dnf upgrade -y
Last metadata expiration check: 0:17:02 ago on Thu Jun 30 14:43:49 2022.
Dependencies resolved.
Nothing to do.
Complete!
[user@sd-template-builder ~]$ git clone https://github.com/freedomofpress/qubes-template-securedrop-workstation
Cloning into 'qubes-template-securedrop-workstation'...
remote: Enumerating objects: 223, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 223 (delta 70), reused 86 (delta 64), pack-reused 124
Receiving objects: 100% (223/223), 111.70 KiB | 2.66 MiB/s, done.
Resolving deltas: 100% (95/95), done.
[user@sd-template-builder ~]$ cd qubes-template-securedrop-workstation
[user@sd-template-builder qubes-template-securedrop-workstation]$ git tag -v 0.3.0
object b81c27fd8476b6fdadc5433a252d2109307adf0d
type commit
tag 0.3.0
tagger Allie Crevier <allie@freedom.press> 1656614893 -0400

qubes-template-securedrop-workstation 0.3.0
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEs7w4of7eC4courm/EXOOCajrhkUFAmK97+0ACgkQEXOOCajr
hkVaLhAAqTtgBjEupffQimlJ3stpGGnAkKzt4HFZ9rOI0d22sn4r7wB5v0P9vgfs
Rn60naWVAdSTL6ZWCkgGjMTIUb9rcV/GS9p6bjqRKB+okg9Ghi+SRUV9KKT+u7cz
TxcXBQYMJ9wvr195oBBKTikJqOb+3N1aoQcMc/zBJLFiKL583qI3E3kKoI3p/387
6FUenjQN0v75RAp5AZHO+8eyUm40c2OKY2V7kcZxFA9fJI9EAW8wk8jV3rwxGn2D
0yB5FSE6l0oXcW3W4FrqWMg+MBcFABKzjv1dNScS8GkHXJVc4elSodbagYHutC+l
NSOZaavQ/verrCvK+lFWYvf+TLrd5sVXr4vIsl9ktT75cmEf2SMKXRxT2pe4QWs5
L9IIhyYjGLIIlQmogE3wVLECawgeokSUkrWtf05lagN+WZ0dvDYuHnIzcGIr4Tfh
CA50oSeo+Pu/jQ2PLv2WGe8kXj3IQs4SKU9MaVwkvjXGmaXVonsAxDSJ2HEQ5Rip
Tjcosd3ePHgYJ8TPA+REJei+6kUV8lJXnwYerwzGOqF6+f5PL2JhiHruCnOOj02B
O2Komh1zBSLERMOXd6zb/SqmA3g1vBowLsYmhBeBNrxarGGxmKamH44Vxtkr7zVi
ojOn/86W6mDZ899Q7sstNUemBVnCsc5KCMRmc62tuk1U3B88XnA=
=pQfB
-----END PGP SIGNATURE-----
gpg: Signature made Thu Jun 30 14:50:45 2022 EDT
gpg:                using RSA key 2359E6538C0613E652955E6C188EDD3B7B22E6A3
gpg: Good signature from "SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>" [ultimate]
[user@sd-template-builder qubes-template-securedrop-workstation]$ git checkout 0.3.0
Note: switching to '0.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b81c27f Merge pull request #28 from freedomofpress/cleanup-unused-legacy-key
[user@sd-template-builder qubes-template-securedrop-workstation]$ make template
umount: qubes-builder/chroot-vm-*/proc: no mount point specified.
Cloning into '/home/user/qubes-template-securedrop-workstation/qubes-builder'...
remote: Enumerating objects: 7039, done.
remote: Counting objects: 100% (361/361), done.
remote: Compressing objects: 100% (168/168), done.
remote: Total 7039 (delta 208), reused 336 (delta 193), pack-reused 6678
Receiving objects: 100% (7039/7039), 4.32 MiB | 7.00 MiB/s, done.
Resolving deltas: 100% (4155/4155), done.
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
gpg: key 188EDD3B7B22E6A3: public key "SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: inserting ownertrust of 6
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/template-securedrop-workstation/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/template-securedrop-workstation/trustdb.gpg: trustdb created
gpg: key 188EDD3B7B22E6A3: public key "SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: inserting ownertrust of 6
Makefile:223: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:223: target 'mgmt-salt.get-sources' given more than once in the same rule
Makefile:225: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:225: target 'mgmt-salt.get-sources-extra' given more than once in the same rule
Makefile:264: target 'builder-debian-vm' given more than once in the same rule
Makefile:264: target 'mgmt-salt-vm' given more than once in the same rule
Makefile:272: target 'builder-debian-dom0' given more than once in the same rule
Makefile:272: target 'mgmt-salt-dom0' given more than once in the same rule
Makefile:628: target 'builder-debian.grep' given more than once in the same rule
Makefile:628: target 'mgmt-salt.grep' given more than once in the same rule
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/builder-debian/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/builder-debian/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2023-07-04
Reset branch 'main'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/builder-rpm/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/builder-rpm/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/vmm-xen/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/vmm-xen/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'xen-4.14'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-vchan-xen/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-vchan-xen/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-qubesdb/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-qubesdb/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-qrexec/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-qrexec/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/linux-utils/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/linux-utils/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-agent-linux/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/core-agent-linux/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/gui-common/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/gui-common/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/gui-agent-linux/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/gui-agent-linux/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-split-gpg/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-split-gpg/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-thunderbird/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-thunderbird/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-pdf-converter/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-pdf-converter/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-img-converter/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-img-converter/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-input-proxy/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-input-proxy/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-usb-proxy/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-usb-proxy/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-snapd-helper/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-linux-snapd-helper/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-shutdown-idle/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-shutdown-idle/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-yubikey/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/app-yubikey/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-base/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-base/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-base-topd/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-base-topd/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-base-config/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-base-config/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-dom0-qvm/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-dom0-qvm/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-dom0-virtual-machines/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-dom0-virtual-machines/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-dom0-update/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/mgmt-salt-dom0-update/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/meta-packages/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/meta-packages/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
gpg: keybox '/home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/linux-template-builder/pubring.kbx' created
gpg: /home/user/qubes-template-securedrop-workstation/qubes-builder/keyrings/git/linux-template-builder/trustdb.gpg: trustdb created
gpg: key DDFA1A3E36879494: public key "Qubes Master Signing Key" imported
gpg: key 063938BA42CFA724: public key "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" imported
gpg: key DA0434BC706E1FCF: public key "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" imported
gpg: Total number processed: 3
gpg:               imported: 3
gpg: no ultimately trusted keys found
gpg: inserting ownertrust of 6
gpg: key DDFA1A3E36879494: "Qubes Master Signing Key" not changed
gpg: key 063938BA42CFA724: "Marek Marczykowski-Górecki (Qubes OS signing key) <marmarek@invisiblethingslab.com>" not changed
gpg: key DA0434BC706E1FCF: "Simon Gaiser (Qubes OS signing key) <simon@invisiblethingslab.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
Reset branch 'master'
Makefile:223: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:223: target 'mgmt-salt.get-sources' given more than once in the same rule
Makefile:225: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:225: target 'mgmt-salt.get-sources-extra' given more than once in the same rule
Makefile:264: target 'builder-debian-vm' given more than once in the same rule
Makefile:264: target 'mgmt-salt-vm' given more than once in the same rule
Makefile:272: target 'builder-debian-dom0' given more than once in the same rule
Makefile:272: target 'mgmt-salt-dom0' given more than once in the same rule
Makefile:473: target 'mgmt-salt.clean' given more than once in the same rule
Makefile:628: target 'builder-debian.grep' given more than once in the same rule
Makefile:628: target 'mgmt-salt.grep' given more than once in the same rule
Makefile:223: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:223: target 'mgmt-salt.get-sources' given more than once in the same rule
Makefile:225: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:225: target 'mgmt-salt.get-sources-extra' given more than once in the same rule
Makefile:264: target 'builder-debian-vm' given more than once in the same rule
Makefile:264: target 'mgmt-salt-vm' given more than once in the same rule
Makefile:272: target 'builder-debian-dom0' given more than once in the same rule
Makefile:272: target 'mgmt-salt-dom0' given more than once in the same rule
Makefile:473: target 'mgmt-salt.clean' given more than once in the same rule
Makefile:628: target 'builder-debian.grep' given more than once in the same rule
Makefile:628: target 'mgmt-salt.grep' given more than once in the same rule
Extracting templates from packages: 100%
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Moving old data out of the way
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent-browser.socket → /usr/lib/systemd/user/gpg-agent-browser.socket.
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent-extra.socket → /usr/lib/systemd/user/gpg-agent-extra.socket.
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent-ssh.socket → /usr/lib/systemd/user/gpg-agent-ssh.socket.
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent.socket → /usr/lib/systemd/user/gpg-agent.socket.
Created symlink /etc/systemd/user/sockets.target.wants/dirmngr.socket → /usr/lib/systemd/user/dirmngr.socket.
Building database of manual pages ...
Created symlink /etc/systemd/system/timers.target.wants/man-db.timer → /lib/systemd/system/man-db.timer.

Creating config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
/home/user/qubes-template-securedrop-workstation/qubes-builder/qubes-src/mgmt-salt//debian-quilt <series.conf> <patchdir>
/home/user/qubes-template-securedrop-workstation/qubes-builder/qubes-src/mgmt-salt//debian-quilt <series.conf> <patchdir>
/home/user/qubes-template-securedrop-workstation/qubes-builder/qubes-src/mgmt-salt//debian-quilt <series.conf> <patchdir>
/home/user/qubes-template-securedrop-workstation/qubes-builder/qubes-src/mgmt-salt//debian-quilt <series.conf> <patchdir>
/home/user/qubes-template-securedrop-workstation/qubes-builder/qubes-src/mgmt-salt//debian-quilt <series.conf> <patchdir>
Makefile:223: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:223: target 'mgmt-salt.get-sources' given more than once in the same rule
Makefile:225: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:225: target 'mgmt-salt.get-sources-extra' given more than once in the same rule
Makefile:264: target 'builder-debian-vm' given more than once in the same rule
Makefile:264: target 'mgmt-salt-vm' given more than once in the same rule
Makefile:272: target 'builder-debian-dom0' given more than once in the same rule
Makefile:272: target 'mgmt-salt-dom0' given more than once in the same rule
Makefile:473: target 'mgmt-salt.clean' given more than once in the same rule
Makefile:628: target 'builder-debian.grep' given more than once in the same rule
Makefile:628: target 'mgmt-salt.grep' given more than once in the same rule
-> Preparing buster reprepro environment (install reprepro on the host to avoid this)
Extracting templates from packages: 100%
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Moving old data out of the way
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
Adding system-user for exim (v4)
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
exim: DB upgrade, deleting hints-db
Created symlink /etc/systemd/system/multi-user.target.wants/atd.service -> /lib/systemd/system/atd.service.
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
Building database of manual pages ...
Created symlink /etc/systemd/system/timers.target.wants/man-db.timer -> /lib/systemd/system/man-db.timer.
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
Initializing GnuTLS DH parameter file

Creating config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Warning: apt-key output should not be parsed (stdout is not a terminal)
'qubes-mgmt-salt_4.1.14-1+deb11u1_amd64.buildinfo' looks like architecture 'amd64', but this is not listed in the Architecture-Header!
Ignoring as --ignore=surprisingarch given.
'qubes-mgmt-salt_4.1.14-1+deb11u1_amd64.buildinfo' looks like architecture 'amd64', but this is not listed in the Architecture-Header!
Ignoring as --ignore=surprisingarch given.
Skipping inclusion of 'qubes-mgmt-salt' '4.1.14-1+deb11u1' in 'bullseye|main|amd64', as it has already '4.1.14-1+deb11u1'.
Skipping inclusion of 'qubes-mgmt-salt-vm-connector' '4.1.14-1+deb11u1' in 'bullseye|main|amd64', as it has already '4.1.14-1+deb11u1'.
Skipping inclusion of 'qubes-mgmt-salt-dom0' '4.1.14-1+deb11u1' in 'bullseye|main|amd64', as it has already '4.1.14-1+deb11u1'.
Skipping inclusion of 'qubes-mgmt-salt-dom0-formulas' '4.1.14-1+deb11u1' in 'bullseye|main|amd64', as it has already '4.1.14-1+deb11u1'.
Skipping inclusion of 'qubes-mgmt-salt-config' '4.1.14-1+deb11u1' in 'bullseye|main|amd64', as it has already '4.1.14-1+deb11u1'.
Skipping inclusion of 'qubes-mgmt-salt' '4.1.14-1+deb11u1' in 'bullseye|main|source', as it has already '4.1.14-1+deb11u1'.
'qubes-mgmt-salt-base_4.1.4-1+deb11u1_amd64.buildinfo' looks like architecture 'amd64', but this is not listed in the Architecture-Header!
Ignoring as --ignore=surprisingarch given.
'qubes-mgmt-salt-base-topd_4.1.3-1+deb11u1_amd64.buildinfo' looks like architecture 'amd64', but this is not listed in the Architecture-Header!
Ignoring as --ignore=surprisingarch given.
'qubes-mgmt-salt-base-config_4.1.1-1+deb11u1_amd64.buildinfo' looks like architecture 'amd64', but this is not listed in the Architecture-Header!
Ignoring as --ignore=surprisingarch given.
Makefile:223: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:223: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:223: target 'template-securedrop-workstation.get-sources' given more than once in the same rule
Makefile:223: target 'builder-rpm.get-sources' given more than once in the same rule
Makefile:223: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:223: target 'mgmt-salt.get-sources' given more than once in the same rule
Makefile:223: target 'mgmt-salt.get-sources' given more than once in the same rule
Makefile:225: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:225: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:225: target 'template-securedrop-workstation.get-sources-extra' given more than once in the same rule
Makefile:225: target 'builder-rpm.get-sources-extra' given more than once in the same rule
Makefile:225: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:225: target 'mgmt-salt.get-sources-extra' given more than once in the same rule
Makefile:225: target 'mgmt-salt.get-sources-extra' given more than once in the same rule
Makefile:264: target 'builder-debian-vm' given more than once in the same rule
Makefile:264: target 'builder-debian-vm' given more than once in the same rule
Makefile:264: target 'template-securedrop-workstation-vm' given more than once in the same rule
Makefile:264: target 'builder-rpm-vm' given more than once in the same rule
Makefile:264: target 'builder-debian-vm' given more than once in the same rule
Makefile:264: target 'mgmt-salt-vm' given more than once in the same rule
Makefile:264: target 'mgmt-salt-vm' given more than once in the same rule
Makefile:272: target 'builder-debian-dom0' given more than once in the same rule
Makefile:272: target 'builder-debian-dom0' given more than once in the same rule
Makefile:272: target 'template-securedrop-workstation-dom0' given more than once in the same rule
Makefile:272: target 'builder-rpm-dom0' given more than once in the same rule
Makefile:272: target 'builder-debian-dom0' given more than once in the same rule
Makefile:272: target 'mgmt-salt-dom0' given more than once in the same rule
Makefile:272: target 'mgmt-salt-dom0' given more than once in the same rule
Makefile:473: target 'template-securedrop-workstation.clean' given more than once in the same rule
Makefile:473: target 'mgmt-salt.clean' given more than once in the same rule
Makefile:473: target 'mgmt-salt.clean' given more than once in the same rule
Makefile:628: target 'builder-debian.grep' given more than once in the same rule
Makefile:628: target 'builder-debian.grep' given more than once in the same rule
Makefile:628: target 'template-securedrop-workstation.grep' given more than once in the same rule
Makefile:628: target 'builder-rpm.grep' given more than once in the same rule
Makefile:628: target 'builder-debian.grep' given more than once in the same rule
Makefile:628: target 'mgmt-salt.grep' given more than once in the same rule
Makefile:628: target 'mgmt-salt.grep' given more than once in the same rule
[user@sd-template-builder qubes-template-securedrop-workstation]$ sha256sum build
build-workstation-template  builder.conf                
[user@sd-template-builder qubes-template-securedrop-workstation]$ sha256sum qubes-builder/qubes-src/linux-template-builder/rpm/noarch/qubes-template-securedrop-workstation-bullseye-4.0.6-202206301923.noarch.rpm 
aebef8779e6d6a64329b5b26b5e5950f524f5e35a2c525275b67bdaadc05a580  qubes-builder/qubes-src/linux-template-builder/rpm/noarch/qubes-template-securedrop-workstation-bullseye-4.0.6-202206301923.noarch.rpm

